---
- name: create vnet
  azure_rm_virtualnetwork:
    name: vnet01
    resource_group: phonebookApp
    address_prefixes_cidr:
    - "10.2.0.0/16"
    - "172.1.0.0/16"
    tags:
      env: testing
    state: present
  tags:
  - recipe2

- name: create public ip
  azure_rm_publicipaddress:
    resource_group: phonebookApp
    name: pip01
    allocation_method: Static
    domain_name: ox-phonebook
    state: present
  register: publicip
  tags:
  - recipe3

- name: show public IP
  debug:
    msg: "{{ publicip['ip_address'] }}"
  tags:
  - recipe3

- name: create subnet
  azure_rm_subnet:
    name: subnet01
    virtual_network_name: vnet01
    resource_group: phonebookApp
    address_prefix_cidr: "10.2.0.0/24"
    state: present
    # security_group_name: mysg01
  tags:
  - recipe5

- name: create nic for pip
  azure_rm_networkinterface:
    name: nic02
    resource_group: phonebookApp
    virtual_network_name: vnet01
    subnet_name: subnet01
    public_ip_address_name: pip01
    security_group_name: mysg01
    state: present
  register: nic2
  tags:
  - recipe4

- name: show private ip
  debug:
    msg: "{{ nic2.ip_configuration.private_ip_address }}"
  tags:
  - recipe2

  - name: Create network security group
  azure_rm_securitygroup:
    resource_group: phonebookApp
    name: mysg01
    purge_rules: yes
    rules:
    - name: 'AllowSSH'
      protocol: TCP
      source_address_prefix: *
      destination_port_range: 22
      access: Allow
      priority: 100
      direction: Inbound
    - name: 'AllowHTTP'
      protocol: TCP
      source_address_prefix: *
      destination_port_range: 80
      priority: 101
      direction: Inbound
    - name: 'AllowHTTPS'
      protocol: TCP
      source_address_prefix: *
      destination_port_range: 443
      priority: 102
      direction: Inbound
    - name: 'DenyAll'
      protocol: TCP
      source_address_prefix: *
      destination_port_range: *
      priority: 103
      direction: Inbound
  tags:
    - recipe5